version: '3.4'

services:
  memorystore:
    image: ${DOCKER_REGISTRY-}memorystore
    ports:
      - 8082:8080
      - 8083:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080;http://+:8081
    build:
      # dockerignore file should be in the context directory
      context: .
      dockerfile: ../MemoryStore/Dockerfile

  externalclient:
     image:  ${DOCKER_REGISTRY-}externalclient
     build:
      context: .
      dockerfile: ../ExternalClient/Dockerfile
