global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:

scrape_configs:
  - job_name: 'memorystore'
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8082']
  - job_name: externalclient
    scheme: http
    metrics_path: /metrics
    static_configs:
    - targets: ['host.docker.internal:1234']
  - job_name: zookeeper
    static_configs:
    - targets: ['host.docker.internal:7000']
